baseurl = "https://example.com"
title = "Wellcome"
copyright = "&copy; 2016 Ali Sarvghad"
languageCode = "en-us"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""


[params]
  name = "Ali Sarvghad"
  role = "Postdoctoral Fellow"
  organization = "University California, San Diego"
  avatar = "headshot.jpg"
  email = "asarvgha@eng.ucsd.edu"
  address = "Dept of Computer Science and Engineering, University of California, San Diego, 9500 Gilman Drive, La Jolla, CA 92093-0404  U.S.A."
  phone = "778 922 4414"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:asarvgha@eng.ucsd.edu" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:asarvgha@eng.ucsd.edu"

  #[[params.social]]
   # icon = "twitter"
   # icon_pack = "fa"
   # link = "//twitter.com/asarv"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=XoCXYBQAAAAJ&hl=en"

	[[params.social]]
	icon = "linkedin"
	icon_pack = "fa"
	link = "https://www.linkedin.com/in/ali-sarvghad-2b897231"

  #[[params.social]]
  # icon = "github"
  # icon_pack = "fa"
  #link = "//github.com/gcushen"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 2


[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 3

#[[menu.main]]
 # name = "Teaching"
 # url = "#teaching"
  #weight = 4

[[menu.main]]
name = "CV"
  url = "pdf/cv.pdf"
  weight = 5


[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6


